### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by Turbo87** [kellyselden/ember-tree#133]
I'm seeing an AJAX 404 error on the console, but not much more.

**Comment by kellyselden** [comment]
Hmm it was working for me yesterday when I was updating dependencies. I also added an acceptance test so it's working on CI. I would be open to debugging via slack.

**Comment by kellyselden** [comment]
OOOOH you mean the github pages demo. Yes I see it now. I will look into it.

**Comment by kellyselden** [comment]
Should be fixed now. Had to enable mirage in production. Thanks for the heads up!
